version: "3.8"

services:
  seafile-memcached:
    container_name: seafile-memcached
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    image: memcached:alpine
    entrypoint: memcached -m 256
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "false"

networks:
  default:
    external: true
    name: $NETWORK
